### PR TITLE
Fix contributing test

### LINKED ISSUE #1157: 2.2.1 testunit error
1 error on testunit that I can't figure out if it is missing some dependency.

Any clues?
Thanks

```
platform freebsd15 -- Python 3.11.9, pytest-8.1.1, pluggy-1.5.0 -- /usr/local/bin/python3.11
cachedir: .pytest_cache
rootdir: /wrkdirs/usr/ports/multimedia/py-subliminal/work-py311/subliminal-2.2.1
configfile: pyproject.toml
testpaths: tests
collected 367 items / 1 error

====================================================================================================== ERRORS ======================================================================================================
_______________________________________________________________________________________ ERROR collecting tests/test_score.py _______________________________________________________________________________________
ImportError while importing test module '/wrkdirs/usr/ports/multimedia/py-subliminal/work-py311/subliminal-2.2.1/tests/test_score.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_score.py:7: in <module>
    from subliminal.score import compute_score, episode_scores, movie_scores, solve_episode_equations, solve_movie_equations
E   ImportError: cannot import name 'solve_episode_equations' from 'subliminal.score' (/wrkdirs/usr/ports/multimedia/py-subliminal/work-py311/subliminal-2.2.1/subliminal/score.py)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================================= 1 error in 0.16s =================================================================================================
*** Error code 2
```

### PR DESCRIPTION
**Pull request by getzze**
fixes #1157

### CODE REVIEW

File: changelog.d/1157.doc.rst [hunk 1]
```diff
@@ -0,0 +1 @@
+Install with docs and test feature in development mode
```
Comment (ptrcnull) [inline changelog.d/1157.doc.rst:1]:
```suggestion
Add installing docs and test dependencies when contributing
```

maybe something like this? the current message makes it feel like Subliminal is installing some stuff on its own

Comment (getzze) [reply changelog.d/1157.doc.rst]: Thanks!

**Review by ptrcnull — APPROVED** [review]
